version: '3.8'

services:
  web:
    build: ./web
    ports:
      - "8000:80"
    volumes:
      - ./secrets:/secrets:ro
      - ./web/logs:/var/log/apache2
    environment:
      - APP_KEY=K3yR4h4s14_$3cr3t!
      - APACHE_RUN_USER=www-data
      - APACHE_RUN_GROUP=www-data
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    networks:
      - ctf-net

networks:
  ctf-net:
    driver: bridge
    internal: true